name: Create Release Branch

on:
  workflow_run:
    workflows: ["Create Tag"]
    types: ["completed"]

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current version
        run: |
          VERSION=$(gh release view --json tagName --jq .tagName)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release branch
        run: |
          RELEASE_BRANCH="release/${VERSION}"
          git fetch
          git checkout dev
          git pull
          git checkout -b $RELEASE_BRANCH
          git push origin $RELEASE_BRANCH
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
