on:
  push:
    branches:
    - feature/**

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "Merge feature/${GITHUB_REF_NAME} into dev" 
            --body "Automated PR from feature/${GITHUB_REF_NAME} to dev" 
            --head "feature/${GITHUB_REF_NAME}" 
            --base "dev"
