name: Create Release Branch

on:
  push:
    branches:
      - dev

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create release branch
        run: |
          RELEASE_BRANCH="release/v${VERSION}"
          git checkout -b $RELEASE_BRANCH dev
          git push origin $RELEASE_BRANCH