name: Create Release Branch

on:
  push:
    branches:
      - dev

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gh
        uses: actions/setup-gh@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current version
        run: |
          VERSION=$(gh release view --json tagName --jq .tagName)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create release branch
        run: |
          RELEASE_BRANCH="release/v${VERSION}"
          git checkout -b $RELEASE_BRANCH dev
          git push origin $RELEASE_BRANCH