on:
  push:
    branches:
    - release/**

permissions:
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull-request branch to main 
        uses: repo-sync/pull-request@v2.12.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into main" 
          pr_body: |                                        
            :crown: *An automated PR*
            _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_